### ISSUE TITLE
Version 1.1.0 no longer shows in Command Palette / does not support .sh files?

### ISSUE THREAD

**Issue by VitosX** [dlech/vscode-chmod#4]
I had to install previous version (1.0.0) for chmod to reappear in Command Palette when editing shell script files. I couldn't find the chmod in right click menu of .sh files either.
I am running macOS 10.14.3.

**Comment by dann1** [comment]
Having to use the mouse instead of the keyboard is really painful and slows down the workflow, it would be really nice to have the option to use several approaches:

- mouse on context menu
- command palette (as previous version)
- keyboard shortcut ([which fails for me](https://github.com/dlech/vscode-chmod/issues/5))
